import { StyleSheet, Platform, StatusBar } from 'react-native';

export const getGlobalStyles = (colors: any, colorScheme: string) => StyleSheet.create({
    mainContainer: { flex: 1, backgroundColor: colors.background },
    container: { paddingHorizontal: 20, paddingBottom: 120 },
    appHeader: { 
        paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ?? 0) + 20 : 60, 
        paddingBottom: 20, 
        paddingHorizontal: 20, 
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        alignItems: 'center',
        backgroundColor: colors.background
    },
    welcomeSubtitle: { fontSize: 16, color: colors.textSecondary },
    welcomeTitle: { fontSize: 26, fontWeight: 'bold', color: colors.text },
    headerButton: { padding: 8, backgroundColor: colors.cardBackground, borderRadius: 99, borderWidth: 1, borderColor: colors.border },
    syncCard: { backgroundColor: colors.primary, borderRadius: 16, padding: 15, flexDirection: 'row', alignItems: 'center', marginVertical: 15, elevation: 4, shadowColor: colors.black, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 4 },
    syncIcon: { marginRight: 15, backgroundColor: 'rgba(255,255,255,0.2)', width: 44, height: 44, justifyContent: 'center', alignItems: 'center', borderRadius: 22 },
    syncCardTitle: { fontSize: 16, fontWeight: 'bold', color: colors.white },
    syncCardSubtitle: { fontSize: 13, color: 'rgba(255, 255, 255, 0.9)', marginTop: 2 },
    grid: { marginTop: 10 },
    actionCard: { 
        backgroundColor: colors.cardBackground, 
        borderRadius: 12, 
        padding: 15, 
        marginBottom: 12, 
        borderWidth: 1, 
        borderColor: colors.border, 
        flexDirection: 'row', 
        alignItems: 'center' 
    },
    actionIconContainer: { 
        width: 40, 
        height: 40, 
        borderRadius: 20, 
        justifyContent: 'center', 
        alignItems: 'center', 
        backgroundColor: colors.background, 
        marginRight: 15 
    },
    actionTextContainer: { flex: 1 },
    actionTitle: { fontSize: 16, fontWeight: 'bold', color: colors.text },
    actionSubtitle: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
    actionChevron: { color: colors.textSecondary },
    separator: { height: 1, backgroundColor: colors.border, marginVertical: 25 },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', color: colors.text, marginLeft: 10 },
    offlineContainer: { backgroundColor: colors.cardBackground, padding: 20, borderRadius: 16, borderWidth: 1, borderColor: colors.border },
    offlineStatusContainerSuccess: { backgroundColor: 'rgba(40, 167, 69, 0.1)', padding: 12, borderRadius: 10, marginBottom: 15, borderWidth: 1, borderColor: 'rgba(40, 167, 69, 0.3)' },
    offlineStatusContainerEmpty: { backgroundColor: 'rgba(255, 193, 7, 0.1)', padding: 12, borderRadius: 10, marginBottom: 15, borderWidth: 1, borderColor: 'rgba(255, 193, 7, 0.3)' },
    offlineStatusText: { textAlign: 'center', fontSize: 13, color: colors.text, fontWeight: '500' },
    offlineButton: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', backgroundColor: colors.primary, paddingVertical: 15, borderRadius: 12, gap: 10, elevation: 3 },
    offlineButtonText: { color: colors.white, fontSize: 16, fontWeight: 'bold' },
    offlineDescription: { fontSize: 13, color: colors.textSecondary, textAlign: 'center', marginTop: 15 },
    footerInfo: { 
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        alignItems: 'center', 
        paddingVertical: 15, 
        paddingHorizontal: 20, 
        borderTopWidth: 1, 
        borderColor: colors.border, 
        backgroundColor: colors.background 
    },
    dateText: { fontSize: 14, color: colors.textSecondary, fontWeight: '500' },
    timeText: { fontSize: 13, color: colors.textSecondary, opacity: 0.8 },
    connectionPill: { flexDirection: 'row', alignItems: 'center', paddingVertical: 5, paddingHorizontal: 10, borderRadius: 15, gap: 6 },
    onlinePill: { backgroundColor: colors.success },
    offlinePill: { backgroundColor: colors.error },
    connectionPillText: { color: colors.white, fontSize: 12, fontWeight: 'bold' },
    floatingButton: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 8,
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
});
